name: Preprocessing Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn mlflow
      - name: Run MLflow project
        run: |
          mlflow run . --env-manager=local
      - name: Commit processed data
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add dataset/processed/iris_processed.csv
          git commit -m "Update processed dataset" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
